### ISSUE TITLE
Add Docker documentation for running in interactive mode

### ISSUE THREAD

**Issue by jimjshields** [datakind/idi-datadive-2018#47]

**Comment by xtream1101** [comment]
This command is listed in the *Making changes to the code* section of the readme: https://github.com/datakind/idi-datadive-2018#making-changes-to-the-code

**Comment by justalfred** [comment]
Oh. Cool. @jimjshields did you have something else in mind? Or can we close?

**Comment by jimjshields** [comment]
Nope, we can close. Thanks @xtream1101!
