### ISSUE TITLE
EIB Scraper Broken

### ISSUE THREAD

**Issue by mdgis** [datakind/idi-datadive-2018#57]
Wondering if someone could take a look at this -😩... Thanks 

Appears broken for any search term 

![image](https://user-images.githubusercontent.com/7546047/42959520-1ecfd286-8b57-11e8-9706-4c5b48482661.png)

**Comment by justalfred** [comment]
urgh, I have class tonight, but I'm betting it just needs a `sleep`....

**Comment by mdgis** [comment]
No rush  - hope thats it. I was worried the website was changed.
