### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer | EIB & IFC Scrapers

### ISSUE THREAD

**Issue by mdgis** [datakind/idi-datadive-2018#59]
This error is only occurring when running the tool using docker. Also Jim's docker file is out of date so check using a local build. The error sometimes doens't occur if you only run one of the scrapers like (only IFC or only EIB) but if you run both for the same search term it usually occurs. 

Would like to hand off to IDI now that Dustin is back in the US, but really need some help figuring this one out. 

Thanks

**Comment by mdgis** [comment]
Fix may be to downgrade selenium==3.8.0

**Comment by jimjshields** [comment]
Hey guys — sorry about the delay on this — just pushed the latest changes for the Docker image.

Don't have much time now but can try to look into the connection issue with EIB / IFC over the weekend.

**Comment by mdgis** [comment]
hey @jimjshields I followed the build instructions - so think this is under control. Let me know if there is anything I should be aware of though (like something the instructions didn't include possibly) 
Thanks

https://hub.docker.com/r/mikdowd/idi/

**Comment by mdgis** [comment]
#60 Fixed - closing
